version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3000"  # 前端服务
      - "8080:8080"  # 后端服务
    environment:
      - NODE_ENV=production