# docker-compose.yml
version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3008:3000" # Map host port 3008 to container port 3000 (Next.js)
    environment:
      # Define environment variables needed by the client at runtime
      # IMPORTANT: Use the service name 'server' as the hostname
      - NEXT_PUBLIC_API_URL=http://server:8089
      - NEXT_PUBLIC_WS_URL=ws://server:8089/ws
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - server # Optional: Ensures server starts before client attempts connection
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8089:8089" # Map host port 8089 to container port 8089 (Hono/Bun server)
    environment:
      # Add any environment variables the server needs
      - NODE_ENV=production
    volumes:
      # Mount a volume to persist uploaded audio files outside the container
      - ./uploads:/app/uploads
    restart: unless-stopped

# Optional: Define a network if you need more control
# networks:
#   app_network:
#     driver: bridge

# volumes: # Define the volume if you want Docker to manage it
#   uploads_data:
